### ISSUE TITLE
After install, Addon does not appear in addon list in Blender 2.83

### ISSUE THREAD

**Issue by Mehdianim** [iCEE-HAM/io_import_lipSync-blender2.8#1]
Hello, I installed the add on by clicking the Zip file in the Preferences, Addons, Install button.
It says it is installed in the log.
I see the directory it created under C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons.
But when I open the blender list I don't see it. I even search for lipSync, nothing comes up.
I've installed plenty addons before so I'm not sure what is different with this one.

Any help would be great ! 
Thank you

**Comment by iCEE-HAM** [comment]
Hi... Try extract and install only the [.py] file instead of the whole zip.

**Comment by iCEE-HAM** [comment]
> Hello, I installed the add on by clicking the Zip file in the Preferences, Addons, Install button.
> It says it is installed in the log.
> I see the directory it created under C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons.
> But when I open the blender list I don't see it. I even search for lipSync, nothing comes up.
> I've installed plenty addons before so I'm not sure what is different with this one.
> 
> Any help would be great !
> Thank you

**Comment by Mehdianim** [comment]
Hey that worked thank you ! I would recommend you add this install information to your README file since it is not quite Blenders standard process.
Thanks !
